11-4: Linux Kernel work initial commit
I configured a build system for future Linux kernel work
I also added my old "hello world" kernel module to test the build system

SPOILERS: I'm getting an error that I can't seem to resolve...
SHORT VERSION...
./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
See below for the LONG VERSION...

TO DO: DON'T DO NOW:
- Cleanup stale code
- Fix the issue

Changes to be committed:
	new file:   modules/Makefile
	new file:   modules/Makefile_constants
	new file:   modules/hello/Makefile
	new file:   modules/hello/hello.c
	new file:   modules/query/Makefile

vagrant@LDP-CDE-v0:~/Repos/sketchy-idea$ sudo make -C modules/hello
make: Entering directory '/home/vagrant/Repos/sketchy-idea/modules/hello'
All
make --no-print-directory reset
reset
make --no-print-directory teardown
teardown
sudo rmmod hello
rmmod: ERROR: Module hello is not currently loaded
make[2]: [Makefile:89: teardown] Error 1 (ignored)
make --no-print-directory clean
clean
rm -rf *.o *.ko *.mod.* *.symvers *.order *-
make --no-print-directory build
build
make --no-print-directory -I/usr/include/x86_64-linux-gnu -C /usr/src/linux-headers-5.4.0-187 M=/home/vagrant/Repos/sketchy-idea/modules/hello modules
  CC [M]  /home/vagrant/Repos/sketchy-idea/modules/hello/hello.o
In file included from ./include/linux/compiler.h:249,
                 from ./include/linux/init.h:5,
                 from /home/vagrant/Repos/sketchy-idea/modules/hello/hello.c:1:
./include/uapi/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
    5 | #include <asm/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [scripts/Makefile.build:270: /home/vagrant/Repos/sketchy-idea/modules/hello/hello.o] Error 1
make[2]: *** [Makefile:1778: /home/vagrant/Repos/sketchy-idea/modules/hello] Error 2
make[1]: *** [Makefile:68: build] Error 2
make: *** [Makefile:62: all] Error 2
make: Leaving directory '/home/vagrant/Repos/sketchy-idea/modules/hello'